<?php
$translate = $this->plugin('translate');
?>
<section class="section">
  <div class="container">
    <?php if ($this->heading): ?>
      <h2 class="title is-3 is-family-secondary"><?php echo $this->heading; ?></h2>
    <?php endif; ?>

    <?php if($block->dataValue('text')):?>
      <div class="content">
              <?php echo $block->dataValue('text');?>
      </div>
    <?php endif; ?>

    <?php if($this->resources):?>
    <div class="columns <?php echo $block->dataValue('columns');?>">
      <?php
      $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
      $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');

      foreach ($this->resources as $resource):
        $heading = $resource->value($headingTerm, ['default' => $translate('[Untitled]')]);
        $body = $resource->value('dcterms:description');
        if($resourceType == 'item-set'):
          $body = $resource->value('dcterms:description');
        endif;
        $type = $resource->resourceTemplate();
        if($type):
          $type= $type->label();
        elseif($resourceType == 'item-set'):
          $type= 'Collection';
        else:
          $type= "Object";
        endif;
      ?>
      <div class="column <?php echo $block->dataValue('columns');?>">
            <?php
              $mediaurl = "";
              if($resourceType == 'item-set'):
                $media = $resource->thumbnail();
                if($media):
                  if(sizeof($this->resources) <= 2):
                    $mediaurl = str_replace('http:','',$media->assetUrl('large'));
                  else:
                    $mediaurl = str_replace('http:','',$media->assetUrl('medium'));
                  endif;
                endif;
              else:
                $media = $resource->media();
                if($media):
                  if(sizeof($this->resources) <= 2):
                    $mediaurl = str_replace('http:', '', $media[0]->thumbnailUrl('large'));
                  else:
                    $mediaurl = str_replace('http:', '', $media[0]->thumbnailUrl('medium'));
                  endif;
                endif;
              endif;
              $url = $resource->url();
            ?>

            <div class="card equal-height">
              <a href="<?php echo $url;?>">
              <div class="card-bg-img-2"
                style="background:url(<?php echo  $mediaurl;?>) no-repeat center 20%;background-color:#aaa;background-size: cover;"
                >
              </div>
              <div class="card-top">
                <?php if($resource->value('dcterms:date')):?>
                  <h6 class="subtitle is-7 datering"><?php echo date('d-m-Y',strtotime($resource->value('dcterms:date')));?></h6>
                <?php endif;?>
                <h5 class="title is-5 is-family-secondary">
                    <?php echo $resource->value('dcterms:title');?>
                </h5>
              </div>
              <div class="card-content">
                <div class="content">
                  <?php $body = $resource->value('dcterms:description');?>
                  <?php if ($body): ?>
                    <?php
                      if(strlen($body) > 200):
                        $body = substr($body, 0, 200);
                        $body = substr($body, 0, strrpos($body, ' ')).' ...';
                      endif;
                    ?>
                    <p>
                      <?php echo $body; ?>
                    </p>
                  <?php endif; ?>
                </div>
              </div>
            </a>
          </div>
      </div>
      <?php endforeach; ?>
    </div>
    <?php if ($this->linkText):?>
      <div class="has-text-right">
        <?php if($this->linkText == 'All collections'):?>
          <a href="<?php echo $block->page()->site()->url().'/item-set';?>" class="button is-white">
            <?php echo $this->linkText;?>
          </a>
        <?php else:?>
          <a href="<?php echo $block->page()->site()->url().'/page/'.strtolower($type);?>" class="button is-white">
            <?php echo $this->linkText;?>
          </a>
        <?php endif;?>
      </div>
    <?php endif;?>
    <?php endif;?>
  </div>
</section>
