<?php
use Zend\Form\Element\Textarea;

echo $this->blockAttachmentsForm($block);
?>
<h4>Title</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title')); ?>" name="o:block[__blockIndex__][o:data][title]">
  </div>
</div>

<h4>Text</h4>
<?php
  $textarea = new Textarea("o:block[__blockIndex__][o:data][text]");
  $textarea->setAttribute('class', 'block-html full wysiwyg');
  if ($block) {
      $textarea->setAttribute('value', $block->dataValue('text'));
  }
?>
<?php echo $this->formRow($textarea);?>

<?php if(isset($block)):
  $reverse = $block->dataValue('reverse');
else:
  $reverse = 0;
endif;?>
<div class="field">
  <div class="field-meta">
      <label>Reverse</label>
      <a href="#" class="expand" aria-label="Expand" title="Expand"></a>
      <div class="collapsible">
        <div class="field-description">Move text to the left and image to the right (with green overlay)</div>
      </div>
  </div>
  <div class="inputs">
      <input type="checkbox" class="" value="reverse" <?php echo ($reverse == 'reverse' ? 'checked' : '') ?> name="o:block[__blockIndex__][o:data][reverse]">
  </div>
</div>
<?php if(isset($block)):
  $itemurl = $block->dataValue('itemurl');
else:
  $itemurl = '';
endif;?>
<div class="field">
  <div class="field-meta">
      <label>Link image to item?</label>
      <a href="#" class="expand" aria-label="Expand" title="Expand"></a>
      <div class="collapsible">
        <div class="field-description">Add a link to the item related to the image/attachment</div>
      </div>
  </div>
  <div class="inputs">
      <input type="checkbox" class="" value="itemurl" <?php echo ($itemurl == 'itemurl' ? 'checked' : '') ?> name="o:block[__blockIndex__][o:data][itemurl]">
  </div>
</div>
