<section class="section breadcrumb-section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="/">Home</a></li>
        <li><?php echo sprintf($this->translate('Search results'), $query); ?></li>
      </ul>
    </nav>
  </div>
</section>
<section class="section">
  <div class="container">
    <h1 class="title is-2 is-family-secondary"><?php echo sprintf($this->translate('Search results for “%s”'), $query); ?></h1>
    <h2 class="title is-4"><?php echo $this->translate('Pages'); ?></h2>
    <?php if ($pages): ?>
      <div class="content">
        <ul>
            <?php foreach ($pages as $page): ?>
            <li><?php echo $page->link($page->title()); ?></li>
            <?php endforeach; ?>
        </ul>

        <a class="button" href="<?php echo $this->url(
            'site/page-browse',
            ['controller' => 'page', 'action' => 'browse'],
            ['query' => ['fulltext_search' => $query]],
            true
        );?>"><?php echo sprintf($this->translate('View all results (%s total)'), $pagesTotal);?></a>
      </div>
    <?php else: ?>
    <p><?php echo $this->translate('No pages found'); ?></p>
    <?php endif; ?>
    <hr />
    <h2 class="title is-4"><?php echo $this->translate('Items'); ?></h2>
    <?php if ($items): ?>
      <div class="content">
        <ul>
            <?php foreach ($items as $item): ?>
            <li><?php echo $item->link($item->displayTitle()); ?></li>
            <?php endforeach; ?>
        </ul>
        <a class="button" href="<?php echo $this->url(
                'site/resource',
                ['controller' => 'item', 'action' => 'browse'],
                ['query' => ['fulltext_search' => $query]],
                true); ?>"><?php echo sprintf($this->translate('View all results (%s total)'), $itemsTotal);?>
        </a>
      </div>
    <?php else: ?>
    <p><?php echo $this->translate('No items found'); ?></p>
    <?php endif; ?>
  </div>
</section>
