<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
?>
<section class="section breadcrumb-section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<?php echo $site->url();?>">Home</a></li>
        <li><?php echo $item->displayTitle(); ?></li>
      </ul>
    </nav>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="columns">
        <?php if (!$embedMedia && $itemMedia): ?>
          <div class="column is-4">
             <div class="slider-for">
               <?php foreach($itemMedia as $media):?>
                 <div class="has-text-centered">
                   <?php $url = str_replace('http:', '', $media->thumbnailUrl('large'));?>
                   <img src="<?php echo $url;?>">
                 </div>
               <?php endforeach;?>
             </div>
          </div>
        <?php endif; ?>
        <?php $this->trigger('view.show.before'); ?>
        <?php if ($embedMedia && $itemMedia): ?>
          <div class="column is-4">
            <div class="media-embeds">
            <?php foreach ($itemMedia as $media):
                echo $media->render();
            endforeach;
            ?>
            </div>
          </div>
        <?php endif; ?>

        <div class="column">
          <h1 class="title is-3 is-family-secondary"><?php echo $item->displayTitle(); ?></h1>
          <div class="content">
            <?php echo $item->displayDescription();?>
          </div>
          <div class="content">
            <a class="button is-primary" href="#<?php echo $item->value('mmfc:idno');?>">
              <span class="icon">
                <i class="fas fa-eye"></i>
              </span>
              <span>View online</span>
            </a>
            <a class="button" href="#<?php echo $item->value('mmfc:idno');?>">
              <span class="icon">
                <i class="fas fa-list"></i>
              </span>
              <span>View description</span>
            </a>
          </div>
        </div>
      </div>
  </div>
</section>
<?php
//find containers
$query = "";
parse_str("property[0][joiner]=and&property[0][property]=377&property[0][type]=eq&property[0][text]=".$item->value('mmfc:idno')."&resource_class_id[]=&resource_template_id[]=3&item_set_id[]=&site_id=&owner_id=&submit=Search",$query);
$containers = $this->api()->search('items',$query);
$containers = $containers->getContent();
?>
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-9">
        <div id="<?php echo $item->value('mmfc:idno');?>" class="identification metadata">
          <h2 class="title is-2">Manuscript description</h2>
          <?php echo $item->displayValues(); ?>
        </div>
        <?php if($containers):?>
          <?php foreach($containers as $container):?>
            <div id="<?php echo $container->value('mmfc:idno');?>" class="mscontainer metadata">
              <h2 class="title is-2"><?php echo $container->displayTitle();?></h2>
              <div style="font-size:0.9rem;">
                <?php echo $container->displayValues(); ?>
              </div>
            </div>
          <?php endforeach;?>
        <?php endif;?>
      </div>
      <div class="column is-3">
        <div class="floating-nav">
          <ul style="font-size:0.8rem;">
            <li><a href="#<?php echo $item->value('mmfc:idno'); ?>">Manuscript description</a></li>
            <?php if($containers):?>
              <ul style="margin-left: 0.5rem;">
                <?php foreach($containers as $container):?>
                  <li><a href="#<?php echo $container->value('mmfc:idno'); ?>">
                    <span class="icon">
                      <i class="fas fa-caret-right"></i>
                    </span>
                    <span><?php echo $container->displayTitle();?></span>
                  </a></li>
                <?php endforeach;?>
              </ul>
            <?php endif;?>

          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
<script>
  $(document).ready(function(){
    $('.slider-for').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      arrows: true,
      fade: true,
      centerMode: true
    });
    /*$('.slider-nav').slick({
      slidesToShow: 10,
      slidesToScroll: 1,
      asNavFor: '.slider-for',
      focusOnSelect: true
    });*/

    var quickLinks = document.querySelectorAll(".floating-nav a");
    var	positionArray =[], hashArray = [];

    for (var i=0; i<quickLinks.length; i++){
    	hashArray.push(quickLinks[i].href.substring(quickLinks[i].href.indexOf('#')+1));
    }

    for (var i=0; i<hashArray.length; i++){
    	positionArray.push(document.getElementById(hashArray[i]).getBoundingClientRect().top);
    }

    function isActive1(){
    	document.getElementsByClassName('is-active')[0];
    }

    document.addEventListener("scroll", scrollHandler, true);

    function scrollHandler() {
    	currentScrollPosition = document.documentElement.scrollTop;
    	//currentActivePosition = document.getElementsByClassName('is-active')[0].getBoundingClientRect().top;
    	for (var i=1; i<=positionArray.length; i++){
    		if (currentScrollPosition>=positionArray[i-1] && currentScrollPosition < positionArray[i]) {
    			var currentActive = document.getElementsByClassName('is-active')[0];
    				if (currentActive != undefined){
        			currentActive.classList.remove('is-active');
        		}
	        quickLinks[i-1].classList.add('is-active');
  			  break;
  		  }

    		if (currentScrollPosition>positionArray[positionArray.length-1]){
    			var currentActive = document.getElementsByClassName('is-active');
  				var currentActive = document.getElementsByClassName('is-active')[0];
  				if (currentActive != undefined){
      			currentActive.classList.remove('is-active');
    			}
    			quickLinks[quickLinks.length-1].classList.add('is-active');
    			break;
  		 }
  	  }
    };

    for (var i=0; i<quickLinks.length; i++){
    	quickLinks[i].addEventListener('click', function(event){
    		document.removeEventListener('scroll', scrollHandler, true);

    		/**
    		for (var j=0; j<quickLinks.length; j++){
    			if (quickLinks[j].classList.contains('is-active')){
    				quickLinks[j].classList.remove('is-active');
    			}
    		}
    		**/

    		isActive = document.getElementsByClassName('is-active')[0];

    		if (isActive != undefined){
    			isActive.classList.remove('is-active');
    		}

    		this.classList.add('is-active');
    		setTimeout(function(){
        			document.addEventListener("scroll", scrollHandler, true);
    	}, 600);
    	});
    }
  });
</script>
