<section class="section intro-section">
  <div class="container">

      <div class="columns">
          <?php if(sizeof($attachments)>0):?>
          <div class="column is-6">
          <?php else:?>
          <div class="column is-8">  
          <?php endif;?>
            <div class="content">
              <h1 class="title is-1 is-family-secondary"><?php echo $block->dataValue('title');?></h1>
              <?php echo $block->dataValue('text');?>
            </div>
          </div>
          <?php if(sizeof($attachments)>0):?>
            <div class="column is-6">
              <div class="content">
                  <?php
                    $media = $attachments[0]->media();
                    if($media):
                      $url = $media->thumbnailUrl('large');
                      $url = str_replace('http:', '', $url);
                      ?>
                        <img src="<?php echo $url;?>" class='u-display-block'>
                    <?php endif;?>
                </div>
            </div>
          <?php endif;?>

      </div>
  </div>
</section>
