<div class="section section--no-padding section--6--light intro">
    <div class="container">
        <div class="grid grid--no-gutter">
            <div class="grid__12 grid__6@med flex flex-justify-center">
                <div class="panel panel--lrg panel--light u-pl-0">
                    <!-- breadcrumbs -->
                    <div class="breadcrumb spacer">
                        <span itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
                            <a href="<?php echo "/";?>" itemprop="url" class="breadcrumb__item"><span itemprop="title">Home</span></a>
                        </span>
                        <?php
                          $flat = filter_bc(flattenArray($block->page()->site()->navigation()));
                          //var_dump($flat);
                          $key = array_search($pageid, $flat);

                          $crumbs = "";

                          while(strlen($key) >= 4){
                            $key = explode('|',$key);

                            array_pop($key);
                            array_pop($key);
                            $key = implode('|',$key)."|";


                            if(isset($flat[$key])):
                              $id = $flat[$key];
                              $page = $this->api()->read('site_pages', $id)->getContent();
                              $link = '<a href="'.$page->url().'">'.$page->title().'</a>';
                              $crumbs = $link.'</span>
                                <span itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">'.$crumbs;
                            endif;
                          }
                          //return $crumbs;
                          //$crumbs = get_crumb($flat,$pageid,$this);
                        ?>
                        <span itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">
                          <?php echo $crumbs;?>
                          <span itemprop="title"><?php echo $block->page()->title();?></span>
                        </span>
                    </div>
                    <h1 class="spacer"><?php echo $block->dataValue('title');?></h1>

                    <div class="text--lead spacer">
                        <?php echo $block->dataValue('text');?>
                    </div>
                </div>
            </div>

            <?php if(sizeof($attachments)>0):?>
              <div class="grid__12 grid__6@med">
                  <div class="image--secondary">
                    <?php
                      $media = $attachments[0]->media();
                      if($media):
                        $url = $media->thumbnailUrl('large');
                        $url = str_replace('http:', '', $url);
                        if($block->dataValue('itemurl')):
                          $itemUrl = $media->item()->url();
                          $itemUrl = str_replace('http:', '', $itemUrl);
                          ?>
                          <a href="<?php echo $itemUrl;?>"><img src="<?php echo $url;?>" class='u-display-block'></a>
                        <?php else:?>
                          <img src="<?php echo $url;?>" class='u-display-block'>
                        <?php endif;?>
                      <?php endif;
                    ?>
                  </div>
                  <figcaption style="margin:13px 13px 0px 13px;"><?php echo $attachments[0]->caption();?></figcaption>
              </div>
            <?php endif;?>
        </div>
        </div>
    </div>
</div>

<?php
function flattenArray($arr) {
    $output = [];

    foreach ($arr as $key => $value) {
        if (is_array($value)) {
            foreach(flattenArray($value) as $flattenKey => $flattenValue) {

                $output["${key}.${flattenKey}"] = $flattenValue;
            }
        } else {
            $output[$key] = $value;
        }
    }
    return $output;
}
function filter_bc($arr){
  $output = [];
  foreach($arr as $key=>$value):
    $level = substr_count($key,'links');
    $temp = explode(".", $key);
    $nr = $temp[0];
    $order = '';

    //echo $key."<br />";
    if (strpos($key, 'id') !== false) {

      foreach($temp as $t){
        if($t != 'links' && $t != 'id' && $t != 'data'):
          $order .= $t."|";
        endif;
      }
      $output[$order] = $value;
    }
  endforeach;
  return $output;
}
function get_crumb($flat,$id,$view){
  $key = array_search($id, $flat);
  $crumbs = "";
  if(strlen($key) == 2):
    return $crumbs;
  endif;

  while(strlen($key) >= 4){
    $key = substr($key, 0, -2);
    $id = $flat[$key];
    $crumbs = get_title($id,$view).'</span>
      <span itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">'.$crumbs;

  }
  return $crumbs;
}
function get_crumb2($flat,$id,$view){
  $key = array_search($id, $flat);
  $crumbs = "";
  if(strlen($key) == 2):
    return $crumbs;
  endif;

  while(strlen($key) >= 4){
    $key = substr($key, 0, -2);
    $id = $flat[$key];
    $crumbs = get_title($id,$view).'</span>
      <span itemscope="" itemtype="https://data-vocabulary.org/Breadcrumb" class="breadcrumb__scope">'.$crumbs;

  }
  return $crumbs;
}
function get_title($id,$view){
  $page = $view->api()->read('site_pages', $id)->getContent();
  return '<a href="'.$page->url().'">'.$page->title().'</a>';
}
?>
