<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

// Add headers (css or scripts) to be included for the form.
// The form itself is managed by search-form-advanced.

// FIXME Bug in admin with module Mapping.
if ($this->status()->isAdminRequest()) return;

$assetUrl = $this->plugin('assetUrl');

$this->headLink()
    ->appendStylesheet($assetUrl('jquery-ui.min.css', 'jQueryUI'))
    ->appendStylesheet($assetUrl('vendor/leaflet/leaflet.css', 'PslSearchForm'))
    ->appendStylesheet($assetUrl('css/psl-search-form.css', 'PslSearchForm'));

// Js are prepended to avoid issues with module Mapping, that uses leaflet too.
$this->headScript()
    ->prependFile($assetUrl('js/psl-search-form.js', 'PslSearchForm'), 'text/javascript', ['defer' => 'defer'])
    ->prependFile($assetUrl('vendor/leaflet/leaflet.js', 'PslSearchForm'), 'text/javascript', ['defer' => 'defer'])
    ->prependFile($assetUrl('jquery-ui.min.js', 'jQueryUI'), 'text/javascript', ['defer' => 'defer']);
