<?php
$translate = $this->plugin('translate');
?>
<nav class="pagination" role="navigation" aria-label="pagination">
<?php if ($totalCount): ?>
    <form method="GET" action="">
        <?php echo $this->queryToHiddenInputs(['page']); ?>
        <input type="text" name="page" class="page-input-top" value="<?php echo $currentPage; ?>" size="4" <?php echo ($pageCount == 1) ? 'readonly' : ''; ?> aria-label="<?php echo $translate('Page'); ?>">
        <span class="page-count"><?php echo sprintf($translate('of %s'), $pageCount); ?></span>
    </form>

    <?php if ($currentPage != 1): ?>
    <?php echo $this->hyperlink($translate('Previous'), $previousPageUrl, ['class' => 'pagination-previous', 'title' => $translate('Previous'), 'aria-label' => $translate('Previous')]); ?>
    <?php endif; ?>

    <?php if ($currentPage < $pageCount): ?>
    <?php echo $this->hyperlink($translate('Next'), $nextPageUrl, ['class' => 'pagination-next', 'title' => $translate('Next'), 'aria-label' => $translate('Next')]); ?>
    <?php endif; ?>

    <?php
    $from = $offset + 1;
    $to = ($currentPage < $pageCount) ? $offset + $perPage : $totalCount;
    ?>
    <span class="row-count"><?php echo sprintf($translate('%1$s–%2$s of %3$s'), $from, $to, $totalCount); ?></span>
<?php else: ?>
    <?php echo $translate('0 results'); ?>
<?php endif; ?>
</nav>
